### ISSUE TITLE
1 check

### ISSUE THREAD

**Issue by Vaitekus** [kate-lobatenko/MODUSversus#3]
Отличный результат !
Designs:
1 http://prntscr.com/mtqldq полоска прачется под кнопки,
2 нет стрелки и не верный ховер http://prntscr.com/mtqmmi
3 отступы по дизайну http://prntscr.com/mtqsbq
4 http://prntscr.com/mtqtsv
 5 различный размер картинок http://prntscr.com/mtr0x6
6 http://prntscr.com/mtr9ay страница не до конца готова (глобально кнопки не застилены)

Structure
1 Ховер на родительской линке не должен пропадать при наведении на дроп http://prntscr.com/mtqqcn
2 логотип уже не делают h1 http://prntscr.com/mtqvg8
3 всегда нужно расчитывать что количество текста будет различным http://prntscr.com/mtqx11 . http://prntscr.com/mtqyab
4 Нужно предусмотреть 71 %, 72 % и т.д от 0-100%
5 https://www.w3.org/TR/html5/grouping-content.html#the-blockquote-element . http://prntscr.com/mslpst
6 h3 http://prntscr.com/mtr0nr
7 на мобилах пропал дроп http://prntscr.com/mtr883

Styles:
1 нет ховера http://prntscr.com/mtqpwx
2 Opacity применилось на цвет текста также, а нужно только на  background http://prntscr.com/mtqrj7
3 Добавить отступы http://prntscr.com/mtqt03

**Comment by kate-lobatenko** [comment]
Designs:
1 http://prntscr.com/mtqldq полоска прачется под кнопки,
зроблено

2 нет стрелки и не верный ховер http://prntscr.com/mtqmmi
зроблено

3 отступы по дизайну http://prntscr.com/mtqsbq
зроблено

4 http://prntscr.com/mtqtsv
зроблено

5 различный размер картинок http://prntscr.com/mtr0x6
зроблено

6 http://prntscr.com/mtr9ay страница не до конца готова (глобально кнопки не застилены)
зроблено

Structure
1 Ховер на родительской линке не должен пропадать при наведении на дроп http://prntscr.com/mtqqcn
зроблено

2 логотип уже не делают h1 http://prntscr.com/mtqvg8
зроблено

3 всегда нужно расчитывать что количество текста будет различным http://prntscr.com/mtqx11 . http://prntscr.com/mtqyab
зроблено

4 Нужно предусмотреть 71 %, 72 % и т.д от 0-100%
Що саме мається на увазі? На markup % немає.

5 https://www.w3.org/TR/html5/grouping-content.html#the-blockquote-element . http://prntscr.com/mslpst
зроблено

6 h3 http://prntscr.com/mtr0nr
зроблено

Styles:
1 нет ховера http://prntscr.com/mtqpwx
зроблено

2 Opacity применилось на цвет текста также, а нужно только на background http://prntscr.com/mtqrj7
зроблено

3 Добавить отступы http://prntscr.com/mtqt03
зроблено

**Comment by Vaitekus** [comment]
4 Нужно предусмотреть 71 %, 72 % и т.д от 0-100%
Що саме мається на увазі? На markup % немає.

У вас позиционирование привязано к классу, код должен быть
переиспользованным и если будет стоять задача отобразить 78% для поворота,
Но такого классы нет с transition

чт, 7 мар. 2019 г. в 19:41, kate-lobatenko <notifications@github.com>:
